### ISSUE TITLE
When trying to run sbd

### ISSUE THREAD

**Issue by gradyhouston** [Humblehound/SafariBooksDownloader#1]
Traceback (most recent call last):
  File "/usr/local/bin/sbd", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 3095, in <module>
    @_call_aside
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 3081, in _call_aside
    f(*args, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 3108, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 660, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 673, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 846, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'six>=1.9.0' distribution was not found and is required by robobrowser

**Comment by lmyslinski** [comment]
Hi, it seems to me there is a problem with your python distribution. I just tried installing with python 2.7.12 on a fresh ubuntu 16.04 LTS installation and it worked like a charm. Could you please provide more data like:

- exact python version
- pip version
- operating system

Also could you try running the python console and importing "pkg_resources" and "six" manually? Like this:

~ > python                                                                                                                                                                    humblehound at hh-vbox
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pkg_resources
>>> import six

Thanks for the feedback

**Comment by gradyhouston** [comment]
Hey there! Thanks for the reply!

I'm on MacOS, the Python version is 2.7, pip version is 9.0.1.

I did manually install "six" before posting here:

`Requirement already satisfied: six in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages`

But it still says:

`DistributionNotFound: The 'six>=1.9.0' distribution was not found and is required by robobrowser`

**Comment by lmyslinski** [comment]
"pip install six -U" should help.
